version: '3.8'

services:
  auth-service:
    build: .
    container_name: gc-group-auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb+srv://gcgroupofficial158_db_user:zHfqFKf1vBJhnqY7@cluster0.3iyatym.mongodb.net/gc_group
      - DB_NAME=gc_group
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRE=7d
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - JWT_REFRESH_EXPIRE=30d
      - BCRYPT_ROUNDS=12
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/v1/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gc-group-network

networks:
  gc-group-network:
    driver: bridge
